/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ImportantQuestion {
  'id' : bigint,
  'topic' : string,
  'explanation' : string,
  'answer' : string,
  'questionText' : string,
  'subjectId' : bigint,
}
export interface Quiz {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'timeLimitMinutes' : bigint,
  'subjectId' : bigint,
  'questionIds' : Array<bigint>,
}
export interface QuizAttempt {
  'id' : bigint,
  'completedAt' : bigint,
  'userId' : Principal,
  'answers' : Array<[bigint, string]>,
  'score' : bigint,
  'totalQuestions' : bigint,
  'quizId' : bigint,
}
export interface QuizQuestion {
  'id' : bigint,
  'correctOption' : string,
  'explanation' : string,
  'questionText' : string,
  'optionA' : string,
  'optionB' : string,
  'optionC' : string,
  'optionD' : string,
}
export interface Subject {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addImportantQuestion' : ActorMethod<
    [bigint, string, string, string, string],
    bigint
  >,
  'addQuiz' : ActorMethod<
    [string, bigint, string, bigint, Array<bigint>],
    bigint
  >,
  'addQuizQuestion' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'addSubject' : ActorMethod<[string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteImportantQuestion' : ActorMethod<[bigint], undefined>,
  'deleteQuiz' : ActorMethod<[bigint], undefined>,
  'deleteQuizQuestion' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getImportantQuestionsBySubject' : ActorMethod<
    [bigint],
    Array<ImportantQuestion>
  >,
  'getQuizWithQuestions' : ActorMethod<
    [bigint],
    { 'quiz' : [] | [Quiz], 'questions' : Array<QuizQuestion> }
  >,
  'getQuizzesBySubject' : ActorMethod<[bigint], Array<Quiz>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserQuizAttempts' : ActorMethod<[Principal], Array<QuizAttempt>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuizAttempt' : ActorMethod<[bigint, Array<[bigint, string]>], bigint>,
  'updateImportantQuestion' : ActorMethod<
    [bigint, bigint, string, string, string, string],
    undefined
  >,
  'updateQuiz' : ActorMethod<
    [bigint, string, bigint, string, bigint, Array<bigint>],
    undefined
  >,
  'updateQuizQuestion' : ActorMethod<
    [bigint, string, string, string, string, string, string, string],
    undefined
  >,
  'updateSubject' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];