/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ImportantQuestion = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'explanation' : IDL.Text,
  'answer' : IDL.Text,
  'questionText' : IDL.Text,
  'subjectId' : IDL.Nat,
});
export const Quiz = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timeLimitMinutes' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'questionIds' : IDL.Vec(IDL.Nat),
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'correctOption' : IDL.Text,
  'explanation' : IDL.Text,
  'questionText' : IDL.Text,
  'optionA' : IDL.Text,
  'optionB' : IDL.Text,
  'optionC' : IDL.Text,
  'optionD' : IDL.Text,
});
export const QuizAttempt = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : IDL.Int,
  'userId' : IDL.Principal,
  'answers' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'quizId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addImportantQuestion' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addQuiz' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'addQuizQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addSubject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteImportantQuestion' : IDL.Func([IDL.Nat], [], []),
  'deleteQuiz' : IDL.Func([IDL.Nat], [], []),
  'deleteQuizQuestion' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getImportantQuestionsBySubject' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ImportantQuestion)],
      ['query'],
    ),
  'getQuizWithQuestions' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'quiz' : IDL.Opt(Quiz),
          'questions' : IDL.Vec(QuizQuestion),
        }),
      ],
      ['query'],
    ),
  'getQuizzesBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Quiz)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserQuizAttempts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(QuizAttempt)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuizAttempt' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      [IDL.Nat],
      [],
    ),
  'updateImportantQuestion' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateQuiz' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)],
      [],
      [],
    ),
  'updateQuizQuestion' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ImportantQuestion = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'explanation' : IDL.Text,
    'answer' : IDL.Text,
    'questionText' : IDL.Text,
    'subjectId' : IDL.Nat,
  });
  const Quiz = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timeLimitMinutes' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'questionIds' : IDL.Vec(IDL.Nat),
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'correctOption' : IDL.Text,
    'explanation' : IDL.Text,
    'questionText' : IDL.Text,
    'optionA' : IDL.Text,
    'optionB' : IDL.Text,
    'optionC' : IDL.Text,
    'optionD' : IDL.Text,
  });
  const QuizAttempt = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : IDL.Int,
    'userId' : IDL.Principal,
    'answers' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'quizId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addImportantQuestion' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addQuiz' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'addQuizQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSubject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteImportantQuestion' : IDL.Func([IDL.Nat], [], []),
    'deleteQuiz' : IDL.Func([IDL.Nat], [], []),
    'deleteQuizQuestion' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getImportantQuestionsBySubject' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ImportantQuestion)],
        ['query'],
      ),
    'getQuizWithQuestions' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'quiz' : IDL.Opt(Quiz),
            'questions' : IDL.Vec(QuizQuestion),
          }),
        ],
        ['query'],
      ),
    'getQuizzesBySubject' : IDL.Func([IDL.Nat], [IDL.Vec(Quiz)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserQuizAttempts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(QuizAttempt)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuizAttempt' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        [IDL.Nat],
        [],
      ),
    'updateImportantQuestion' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateQuiz' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)],
        [],
        [],
      ),
    'updateQuizQuestion' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };